# specify the node base image with your desired version node:<version>
FROM node:18-alpine

# ENV DIRPATH = . 

# WORKDIR $DIRPATH

# RUN pwd

# replace this with your application's default port
EXPOSE 3000

CMD ["node", "index.js"]