# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    image: nodejs-app
    build: 
      context: ./
      dockerfile: ./Dockerfile
  
  mongo:
    image: mongo:7.0.6
    restart: always
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017:27017